apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-n65l
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-n65l@sha256:6aa0c6f44a5b1f7a48fb941fbeb9e0d474c2d6fcccc8d63794a5d89cd979abdf
        name: my-nodejs
        resources: {}
status: {}
